name: Continuous Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['web_app/**', 'twitter_analyzer/**']
  
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  poetry_install:
    name: Install poetry
    uses: ./.github/workflows/poetry_install.yml
 
  unit_testing:
    needs: poetry_install
    secrets: 
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
    uses: ./.github/workflows/unit_testing.yml

  integration_testing:
    needs: poetry_install
    uses: ./.github/workflows/integration_testing.yml 

  backend_deployment:
    needs: integration_testing
    name: Backend Deployment
    secrets: 
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    uses: ./.github/workflows/backend_deployment.yml

  frontend_deployment:
    needs: integration_testing
    name: Frontend Deployment
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    uses: ./.github/workflows/frontend_deployment.yml