name: Continuous Deployment Pipeline

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ['main']
    paths: ['web_app/**', 'twitter_analyzer/**']
  
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  poetry_install:
    name: Install poetry
    uses: ./.github/workflows/poetry_install.yml
 
  unit_testing:
    needs: poetry_install
    uses: ./.github/workflows/unit_testing.yml

  integration_testing:
    needs: poetry_install
    uses: ./.github/workflows/integration_testing.yml 

  backend_deployment:
    needs: integration_testing
    name: Backend Deployment
    uses: ./.github/workflows/backend_deployment.yml

  frontend_deployment:
    needs: integration_testing
    name: Frontend Deployment
    uses: ./.github/workflows/frontend_deployment.yml