name: Unit Test & Upload Coverage

on: 
  workflow_call:
    secrets:
        GDRIVE_CREDENTIALS_DATA:
          description: 'Credentials to download the necessary data'
          required: true

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
 
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment

      - name: Test
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          source $VENV
          dvc pull
          python -m pytest tests/unitary/
